### ISSUE TITLE
downloadClass

### ISSUE THREAD

**Issue by IbrahimAssi** [SoftwareConstructionBZU/multipartDownloader#5]
Dears 

in operation download  need path download folder , file name and file type How can get them?

i think can select a specific folder path to use it as folder download
but file name and file type, How can get them? I write it as static until solve this problem.

part of code in download constructor -------------------------

    public Download(String url) throws Exception
    {
        this.mainFile="FILE1";
        this.tempFile="TMP";
        this.fileType="mp3";

.........

BR

**Comment by saadhroub** [comment]
Dear Ibrahim
there is no need to save the file, we only are required to return the file as an input stream to the interface which was sent by Dr. Afaneh
