### ISSUE TITLE
read size the file form input stream

### ISSUE THREAD

**Issue by IbrahimAssi** [SoftwareConstructionBZU/multipartDownloader#8]
i have a problem when try read file size file from input stream
i known should read first 4 byte but how can convert this 4 byte to integer?

**Comment by saadhroub** [comment]
after searching for this problem in Google, I found the following suggested solution, please try it
Integer.toBinaryString(b & 0xFF);

use this to unsigned number

**Comment by IbrahimAssi** [comment]
Thanks
